// app/src/app/(app)/lease/create.tsx
import { BottomSheetModalProvider } from '@gorhom/bottom-sheet';
import { router } from 'expo-router';
import React from 'react';
import { showMessage } from 'react-native-flash-message';

import { useAddLeaseSheet } from '@/api/lease/use-lease-mutations';
import { LeaseForm } from '@/components/lease/lease-form';
import type { LeaseFormData } from '@/lib/types/models';
import { VehicleType } from '@/lib/types/models';

const defaultFormData: LeaseFormData = {
  sheet_name: '',
  sales_consultant: '',
  dealership_name: '',
  vehicle_type: VehicleType.CAR,
  vehicle_year: '',
  vehicle_make: '',
  vehicle_model: '',
  vehicle_trim: '',
  msrp: 0,
  dealer_contribution: 0,
  trade_in: 0,
  doc_fee: 0,
  acquisition_fee: 0,
  misc_fees: 0,
  lease_cash: 0,
  down_payment: 0,
  sales_tax_percent: 0,
  money_factor: 0,
  residual_percent: 50,
  lease_term: 36,
  start_date: new Date().toISOString().split('T')[0],
  contact_email: '',
  contact_phone: '',
  notes: '',
};

export default function LeaseCreateScreen() {
  const { mutate: createSheet, isPending } = useAddLeaseSheet();

  const handleSubmit = (data: LeaseFormData) => {
    createSheet(data, {
      onSuccess: () => {
        showMessage({
          message: 'Success',
          description: 'Lease estimate created successfully',
          type: 'success',
        });
        router.back();
      },
      onError: (error) => {
        showMessage({
          message: 'Error',
          description: error.message || 'Failed to create estimate',
          type: 'danger',
        });
      },
    });
  };

  return (
    <BottomSheetModalProvider>
      <LeaseForm
        initialData={defaultFormData}
        onSubmit={handleSubmit}
        isSubmitting={isPending}
        submitLabel="Create Estimate"
      />
    </BottomSheetModalProvider>
  );
}

// resources/js/Pages/Estimates/Leasing/Create.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Head, router } from '@inertiajs/vue3'
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'
import LeaseForm from '@/Components/LeaseForm.vue'
import EstimateSummary from '@/Components/EstimateSummary.vue'
import { LeaseFormData, FormErrors, VehicleType, User, Profile } from '@/types'
import { LeaseCalculator } from '@/utils/leaseCalculator'
import axios from 'axios'

interface Props {
    user: User;
    profile: Profile;
}

const props = defineProps<Props>();

const form = ref<LeaseFormData>({
    sheet_name: '',
    sales_consultant: '',
    dealership_name: '',
    vehicle_type: VehicleType.CAR,
    vehicle_year: '',
    vehicle_make: '',
    vehicle_model: '',
    vehicle_trim: '',
    msrp: '',
    dealer_contribution: '',
    trade_in: '',
    doc_fee: '',
    acquisition_fee: '',
    misc_fees: '',
    lease_cash: '',
    down_payment: '',
    sales_tax_percent: '',
    money_factor: '',
    residual_percent: '',
    lease_term: '',
    start_date: '',
    contact_email: '',
    contact_phone: '',
    notes: ''
})

const loading = ref(false)
const errors = ref<FormErrors>({})

const calculatedCapitalizedCost = computed(() => {
    const calculator = new LeaseCalculator(form.value)
    return calculator.calculateNetCapCost()
})

const submitForm = async () => {
    loading.value = true
    errors.value = {}

    try {
        await axios.post('/api/vehicle-lease-sheets', form.value)
        router.visit('/estimates/leasing')
    } catch (error: any) {
        if (error.response?.data?.errors) {
            errors.value = error.response.data.errors
        } else {
            console.error('Error creating lease sheet:', error)
        }
    } finally {
        loading.value = false
    }
}

const calculateTotals = () => {
    return calculatedCapitalizedCost.value
}
</script>

<template>
    <Head title="Create Lease Estimate" />

    <AuthenticatedLayout :user="props.user" :profile="props.profile">
        <main class="-mt-16 pb-8 flex-1">
            <div class="mx-auto max-w-3xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
                <div class="grid grid-cols-1 items-start gap-4 lg:grid-cols-3 lg:gap-8">
                    <div class="grid grid-cols-1 gap-4 lg:col-span-2">
                        <section aria-labelledby="create-lease-estimate-title">
                            <LeaseForm
                                :form="form"
                                :errors="errors"
                                :loading="loading"
                                title="Create Lease Estimate"
                                back-url="/estimates/leasing"
                                @submit="submitForm"
                                @calculate="calculateTotals"
                            />
                        </section>
                    </div>

                    <div class="grid grid-cols-1 gap-4">
                        <EstimateSummary
                            estimate-type="lease"
                            :calculated-value="calculatedCapitalizedCost"
                        />
                    </div>
                </div>
            </div>
        </main>
    </AuthenticatedLayout>
</template>
