// app/src/app/(app)/(tabs)/watch/index.tsx
import { Link, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { ActivityIndicator, RefreshControl } from 'react-native';

import { useWatch } from '@/api/watch';
import { ProductCard } from '@/components/tracker/product-card';
import { Button, FloatingAddButton, Pressable, ScreenContainer, ScrollView, Text, View } from '@/components/ui';
import colors from '@/components/ui/colors';
import type { PriceTrackerFilter } from '@/lib/types/models';

const FILTERS: { key: PriceTrackerFilter; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'active', label: 'Active' },
  { key: 'paused', label: 'Paused' },
  { key: 'target_reached', label: 'Target Reached' },
  { key: 'price_drops', label: 'Price Drops' },
];

export default function TrackerListScreen() {
  const router = useRouter();
  const [filter, setFilter] = useState<PriceTrackerFilter>('all');
  const { data, isLoading, isError, refetch, isRefetching } = useWatch();

  if (isLoading) {
    return (
      <ScreenContainer className="items-center justify-center">
        <ActivityIndicator size="large" color={colors.accent.DEFAULT} />
        <Text className="mt-4 text-neutral-600 dark:text-neutral-400">Loading products...</Text>
      </ScreenContainer>
    );
  }

  if (isError) {
    return (
      <ScreenContainer className="items-center justify-center p-6">
        <Text className="mb-4 text-center text-lg text-danger-600">Failed to load products</Text>
        <Button label="Try Again" onPress={() => refetch()} />
      </ScreenContainer>
    );
  }

  const allProducts = data?.tracked_products ?? [];

  // Filter products based on selected filter
  const filteredProducts = allProducts.filter((product) => {
    switch (filter) {
      case 'active':
        return product.is_active;
      case 'paused':
        return !product.is_active;
      case 'target_reached':
        return product.current_price <= product.target_price;
      case 'price_drops':
        return product.price_drop_percentage > 0;
      default:
        return true;
    }
  });

  return (
    <ScreenContainer>
      {/* Filter chips */}
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        className="max-h-14 border-b border-neutral-200 bg-white dark:border-charcoal-700 dark:bg-charcoal-800"
        contentContainerStyle={{
          paddingHorizontal: 16,
          paddingVertical: 8,
          gap: 8,
        }}
      >
        {FILTERS.map((f) => (
          <Pressable
            key={f.key}
            onPress={() => setFilter(f.key)}
            className={`rounded-full px-4 py-2 ${
              filter === f.key ? 'bg-accent' : 'bg-neutral-200 dark:bg-charcoal-700'
            }`}
          >
            <Text
              className={`text-sm font-medium ${
                filter === f.key ? 'text-white' : 'text-neutral-700 dark:text-neutral-300'
              }`}
            >
              {f.label}
            </Text>
          </Pressable>
        ))}
      </ScrollView>

      <ScrollView
        className="flex-1"
        contentContainerStyle={{ padding: 16, paddingBottom: 120 }}
        refreshControl={<RefreshControl refreshing={isRefetching} onRefresh={refetch} />}
      >
        {filteredProducts.length === 0 ? (
          <View className="flex-1 items-center justify-center py-20">
            <Text className="mb-2 text-xl font-semibold text-neutral-700 dark:text-neutral-300">
              {allProducts.length === 0 ? 'No Tracked Products' : 'No Products Match Filter'}
            </Text>
            <Text className="mb-6 text-center text-neutral-500 dark:text-neutral-400">
              {allProducts.length === 0
                ? 'Start tracking products to get notified when prices drop.'
                : 'Try selecting a different filter.'}
            </Text>
            {allProducts.length === 0 && (
              <Link href="/(app)/watch/create" asChild>
                <Button label="Track a Product" />
              </Link>
            )}
          </View>
        ) : (
          <View className="gap-4">
            {filteredProducts.map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </View>
        )}
      </ScrollView>

      {/* Floating Add Button */}
      <FloatingAddButton
        onPress={() => router.push('/(app)/watch/create')}
        color={colors.accent.DEFAULT}
        accessibilityLabel="Track new product"
      />
    </ScreenContainer>
  );
}

// web/src/pages/watch/Index.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { RouterLink } from 'vue-router'
import PageHeader from '@/components/PageHeader.vue'
import Card from '@/components/Card.vue'
import Badge from '@/components/Badge.vue'
import Spinner from '@/components/Spinner.vue'
import { TagIcon, PlusIcon, TrashIcon, EyeIcon, ArrowPathIcon, EnvelopeIcon, DevicePhoneMobileIcon } from '@heroicons/vue/24/outline'
import { formatCurrency } from '@/utils/formatters'
import { formatRelativeTime } from '@/utils/time'
import { watchApi, type TrackedProduct } from '@/api/watch'

type FilterType = 'all' | 'active' | 'paused'

const products = ref<TrackedProduct[]>([])
const loading = ref(true)
const refreshingId = ref<number | null>(null)
const activeFilter = ref<FilterType>('all')

const filteredProducts = computed(() => {
  if (activeFilter.value === 'all') return products.value
  if (activeFilter.value === 'active') return products.value.filter(p => p.is_active)
  return products.value.filter(p => !p.is_active)
})

const filterCounts = computed(() => ({
  all: products.value.length,
  active: products.value.filter(p => p.is_active).length,
  paused: products.value.filter(p => !p.is_active).length,
}))

const fetchProducts = async () => {
  try {
    const data = await watchApi.getAll()
    products.value = data
  } catch (error) {
    console.error('Error fetching tracked products:', error)
  } finally {
    loading.value = false
  }
}

const deleteProduct = async (id: number) => {
  if (confirm('Are you sure you want to stop tracking this product?')) {
    try {
      await watchApi.delete(id)
      await fetchProducts()
    } catch (error) {
      console.error('Error deleting product:', error)
    }
  }
}

const refreshProduct = async (id: number) => {
  refreshingId.value = id
  try {
    await watchApi.refresh(id)
    await fetchProducts()
  } catch (error) {
    console.error('Error refreshing product:', error)
  } finally {
    refreshingId.value = null
  }
}

const getRetailerName = (product: TrackedProduct): string => {
  return product.retailer?.name || 'Unknown'
}

onMounted(() => {
  fetchProducts()
})
</script>

<template>
  <main class="py-12 flex-1">
    <div class="mx-auto max-w-3xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
      <!-- Header -->
      <PageHeader
        title="Watch"
        description="Track price movement and get notified when they drop"
        back-link="/dashboard"
        back-label="Dashboard"
      >
        <template #actions>
          <RouterLink to="/watch/create">
            <button class="bg-accent hover:bg-accent-dark text-white px-6 py-3 rounded-lg font-medium transition-all duration-150 flex items-center space-x-2">
              <PlusIcon class="h-5 w-5" />
              <span>Track New Product</span>
            </button>
          </RouterLink>
        </template>
      </PageHeader>

      <!-- Quick Filters -->
      <div v-if="!loading && products.length" class="flex items-center gap-2 mb-6">
        <button
          v-for="filter in (['all', 'active', 'paused'] as FilterType[])"
          :key="filter"
          @click="activeFilter = filter"
          :class="[
            'px-4 py-2 rounded-lg text-sm font-medium transition-colors',
            activeFilter === filter
              ? 'bg-accent text-white'
              : 'bg-surface text-text-muted hover:bg-background'
          ]"
        >
          {{ filter === 'all' ? 'All' : filter === 'active' ? 'Active' : 'Paused' }}
          <span class="ml-1.5 text-xs opacity-75">({{ filterCounts[filter] }})</span>
        </button>
      </div>

      <!-- Loading -->
      <div v-if="loading" class="flex items-center justify-center py-12">
        <Spinner size="lg" color="accent" />
      </div>

      <!-- Empty State -->
      <Card v-else-if="!products.length" class="text-center" padding="lg">
        <div class="p-4 rounded-xl bg-accent/10 w-16 h-16 mx-auto mb-4 flex items-center justify-center">
          <TagIcon class="h-8 w-8 text-accent-dark" />
        </div>
        <h3 class="text-lg font-medium text-primary mb-2">No products being tracked</h3>
        <p class="text-text-muted mb-6">Track product prices to understand price movement before you buy</p>
        <RouterLink to="/watch/create">
          <button class="bg-accent hover:bg-accent-dark text-white px-6 py-3 rounded-lg font-medium transition-all duration-150 flex items-center space-x-2 mx-auto">
            <PlusIcon class="h-5 w-5" />
            <span>Track First Product</span>
          </button>
        </RouterLink>
      </Card>

      <!-- Empty Filter State -->
      <Card v-else-if="products.length && !filteredProducts.length" class="text-center" padding="lg">
        <p class="text-text-muted">
          No {{ activeFilter === 'active' ? 'active' : 'paused' }} products.
          <button @click="activeFilter = 'all'" class="text-accent hover:underline">View all</button>
        </p>
      </Card>

      <!-- Products List -->
      <div v-else class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <Card
          v-for="product in filteredProducts"
          :key="product.id"
          variant="interactive"
          padding="none"
          class="overflow-hidden"
        >
          <!-- Product Header -->
          <div class="p-4 border-b border-border">
            <div class="flex items-start justify-between mb-2">
              <div class="flex-1 min-w-0">
                <h3 class="font-medium text-primary truncate">
                  {{ product.product_name || 'Pending lookup...' }}
                </h3>
                <p class="text-xs text-text-muted mt-0.5">
                  {{ getRetailerName(product) }} &middot; {{ product.sku_upc }}
                </p>
              </div>
              <Badge v-if="product.is_active" variant="success" size="sm">Active</Badge>
              <Badge v-else variant="neutral" size="sm">Paused</Badge>
            </div>

            <!-- Notification Methods -->
            <div class="flex items-center gap-2 mt-2">
              <span class="text-xs text-text-muted">Alerts:</span>
              <div class="flex items-center gap-1">
                <EnvelopeIcon
                  v-if="product.notification_method?.includes('email')"
                  class="h-4 w-4 text-accent"
                  title="Email notifications"
                />
                <DevicePhoneMobileIcon
                  v-if="product.notification_method?.includes('push')"
                  class="h-4 w-4 text-accent"
                  title="Push notifications"
                />
              </div>
            </div>
          </div>

          <!-- Price Info -->
          <div class="bg-background p-4">
            <div class="flex items-center justify-between">
              <span class="text-text-muted text-sm">Current Price</span>
              <span class="font-medium text-xl text-success">
                {{ product.current_price ? `$${formatCurrency(product.current_price)}` : '—' }}
              </span>
            </div>
            <div v-if="product.target_price" class="flex items-center justify-between mt-2">
              <span class="text-text-muted text-sm">Target Price</span>
              <span class="font-medium text-primary">${{ formatCurrency(product.target_price) }}</span>
            </div>
            <div v-if="product.last_checked_at" class="text-xs text-text-muted mt-2 text-right">
              Last checked {{ formatRelativeTime(product.last_checked_at) }}
            </div>
            <div v-else class="text-xs text-text-muted mt-2 text-right">
              Not yet checked
            </div>
          </div>

          <!-- Actions -->
          <div class="grid grid-cols-3 gap-px bg-border border-t border-border"">
            <RouterLink :to="`/watch/${product.id}`" class="block">
              <button class="w-full bg-surface hover:bg-background text-text-muted px-2 py-3 text-xs font-medium flex items-center justify-center gap-1.5 transition-colors">
                <EyeIcon class="h-4 w-4" />
                <span>Details</span>
              </button>
            </RouterLink>
            <button
              @click="refreshProduct(product.id)"
              :disabled="refreshingId === product.id"
              class="w-full bg-surface hover:bg-background text-text-muted px-2 py-3 text-xs font-medium flex items-center justify-center gap-1.5 transition-colors disabled:opacity-50"
            >
              <ArrowPathIcon :class="['h-4 w-4', refreshingId === product.id && 'animate-spin']" />
              <span>{{ refreshingId === product.id ? 'Checking...' : 'Refresh' }}</span>
            </button>
            <button
              @click="deleteProduct(product.id)"
              class="w-full bg-surface hover:bg-danger text-danger hover:text-white px-2 py-3 text-xs font-medium flex items-center justify-center gap-1.5 transition-colors"
            >
              <TrashIcon class="h-4 w-4" />
              <span>Delete</span>
            </button>
          </div>
        </Card>

        <!-- Add New Card -->
        <RouterLink to="/watch/create">
          <Card variant="interactive" class="h-full flex flex-col items-center justify-center text-center border-2 border-dashed border-accent/30 hover:border-accent bg-transparent" padding="lg">
            <div class="p-3 rounded-xl bg-accent/10 w-fit mx-auto mb-4">
              <PlusIcon class="h-8 w-8 text-accent-dark" />
            </div>
            <h3 class="text-lg font-medium text-primary mb-2">Track New Product</h3>
            <p class="text-text-muted text-sm">Add a product to monitor its price</p>
          </Card>
        </RouterLink>
      </div>
    </div>
  </main>
</template>
