// app/src/components/finance/finance-form.tsx
import { zodResolver } from '@hookform/resolvers/zod';
import React, { useMemo } from 'react';
import type { Control, UseFormSetValue } from 'react-hook-form';
import { useForm, useWatch } from 'react-hook-form';
import { z } from 'zod';

import {
  CurrencyInput,
  FormSection,
  PercentageInput,
} from '@/components/forms';
import {
  Button,
  ControlledInput,
  ScrollView,
  Select,
  Text,
  View,
} from '@/components/ui';
import { FinanceCalculator, formatCurrencyWithSymbol } from '@/lib/calculators';
import type { FinanceFormData } from '@/lib/types/models';
import { VehicleType } from '@/lib/types/models';

const financeSchema = z.object({
  sheet_name: z.string().min(1, 'Name is required'),
  sales_consultant: z.string().nullable().optional(),
  dealership_name: z.string().nullable().optional(),
  vehicle_type: z.nativeEnum(VehicleType),
  vehicle_year: z.string().nullable().optional(),
  vehicle_make: z.string().nullable().optional(),
  vehicle_model: z.string().nullable().optional(),
  vehicle_trim: z.string().nullable().optional(),
  msrp: z.number().min(0),
  fees: z.number().min(0),
  discounts: z.number().min(0),
  rebates: z.number().min(0),
  down_payment: z.number().min(0),
  sales_tax_percent: z.number().min(0).max(100),
  interest_rate: z.number().min(0).max(100),
  finance_term: z.number().min(1).max(120),
  start_date: z.string(),
  contact_email: z.string().email().nullable().optional().or(z.literal('')),
  contact_phone: z.string().nullable().optional(),
  extra_payments_json: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

interface FinanceFormProps {
  initialData: FinanceFormData;
  onSubmit: (data: FinanceFormData) => void;
  isSubmitting: boolean;
  submitLabel: string;
  onCancel?: () => void;
}

const VEHICLE_TYPE_OPTIONS = [
  { value: VehicleType.CAR, label: 'Car' },
  { value: VehicleType.TRUCK, label: 'Truck' },
  { value: VehicleType.SUV, label: 'SUV' },
];

const TERM_OPTIONS = [
  { value: 24, label: '24 months' },
  { value: 36, label: '36 months' },
  { value: 48, label: '48 months' },
  { value: 60, label: '60 months' },
  { value: 72, label: '72 months' },
  { value: 84, label: '84 months' },
];

export function FinanceForm({
  initialData,
  onSubmit,
  isSubmitting,
  submitLabel,
  onCancel,
}: FinanceFormProps) {
  const { control, handleSubmit, setValue, formState } =
    useForm<FinanceFormData>({
      resolver: zodResolver(financeSchema),
      defaultValues: initialData,
    });
  const watchedValues = useWatch({ control });
  const summary = useMemo(
    () => new FinanceCalculator(watchedValues as FinanceFormData).getSummary(),
    [watchedValues]
  );

  return (
    <View className="flex-1 bg-neutral-100 dark:bg-neutral-900">
      <ScrollView className="flex-1" contentContainerStyle={{ padding: 16 }}>
        <Text>{JSON.stringify(formState.errors)}</Text>
        <SummaryCard summary={summary} />
        <EstimateInfoSection control={control} />
        <VehicleInfoSection
          control={control}
          watchedValues={watchedValues}
          setValue={setValue}
        />
        <PricingSection control={control} />
        <FinancingSection
          control={control}
          watchedValues={watchedValues}
          setValue={setValue}
        />
        <ContactSection control={control} />
        <NotesSection control={control} />
        <AdvancedSection control={control} />
        <View className="h-20" />
      </ScrollView>
      <ActionBar
        onSubmit={handleSubmit(onSubmit)}
        onCancel={onCancel}
        isSubmitting={isSubmitting}
        submitLabel={submitLabel}
      />
    </View>
  );
}

function SummaryCard({
  summary,
}: {
  summary: ReturnType<FinanceCalculator['getSummary']>;
}) {
  return (
    <View className="mb-6 rounded-xl bg-primary-600 p-4">
      <Text className="mb-2 text-white opacity-80">Monthly Payment</Text>
      <Text className="text-3xl font-bold text-white">
        {formatCurrencyWithSymbol(summary.monthlyPayment)}
      </Text>
      <View className="mt-3 flex-row justify-between">
        <View>
          <Text className="text-xs text-white opacity-60">Loan Amount</Text>
          <Text className="text-white">
            {formatCurrencyWithSymbol(summary.loanAmount)}
          </Text>
        </View>
        <View>
          <Text className="text-xs text-white opacity-60">Total Interest</Text>
          <Text className="text-white">
            {formatCurrencyWithSymbol(summary.interestAmount)}
          </Text>
        </View>
        <View>
          <Text className="text-xs text-white opacity-60">Grand Total</Text>
          <Text className="text-white">
            {formatCurrencyWithSymbol(summary.grandTotal)}
          </Text>
        </View>
      </View>
    </View>
  );
}

function EstimateInfoSection({
  control,
}: {
  control: Control<FinanceFormData>;
}) {
  return (
    <FormSection title="Estimate Info">
      <ControlledInput
        control={control}
        name="sheet_name"
        label="Estimate Name"
        placeholder="My Car Estimate"
      />
    </FormSection>
  );
}

type FormProps = {
  control: Control<FinanceFormData>;
  watchedValues: Partial<FinanceFormData>;
  setValue: UseFormSetValue<FinanceFormData>;
};

function VehicleInfoSection({ control, watchedValues, setValue }: FormProps) {
  return (
    <FormSection title="Vehicle Information">
      <Select
        label="Vehicle Type"
        options={VEHICLE_TYPE_OPTIONS}
        value={watchedValues.vehicle_type}
        onSelect={(v) => setValue('vehicle_type', v as VehicleType)}
      />
      <View className="mt-2 flex-row gap-2">
        <View className="flex-1">
          <ControlledInput
            control={control}
            name="vehicle_year"
            label="Year"
            placeholder="2024"
            keyboardType="number-pad"
          />
        </View>
        <View className="flex-1">
          <ControlledInput
            control={control}
            name="vehicle_make"
            label="Make"
            placeholder="Toyota"
          />
        </View>
      </View>
      <View className="flex-row gap-2">
        <View className="flex-1">
          <ControlledInput
            control={control}
            name="vehicle_model"
            label="Model"
            placeholder="Camry"
          />
        </View>
        <View className="flex-1">
          <ControlledInput
            control={control}
            name="vehicle_trim"
            label="Trim"
            placeholder="XLE"
          />
        </View>
      </View>
    </FormSection>
  );
}

function PricingSection({ control }: { control: Control<FinanceFormData> }) {
  return (
    <FormSection title="Pricing">
      <CurrencyInput control={control} name="msrp" label="MSRP" />
      <CurrencyInput control={control} name="fees" label="Fees" />
      <CurrencyInput control={control} name="discounts" label="Discounts" />
      <CurrencyInput control={control} name="rebates" label="Rebates" />
    </FormSection>
  );
}

function FinancingSection({ control, watchedValues, setValue }: FormProps) {
  return (
    <FormSection title="Financing">
      <CurrencyInput
        control={control}
        name="down_payment"
        label="Down Payment"
      />
      <PercentageInput
        control={control}
        name="sales_tax_percent"
        label="Sales Tax"
      />
      <PercentageInput
        control={control}
        name="interest_rate"
        label="Interest Rate (APR)"
      />
      <Select
        label="Loan Term"
        options={TERM_OPTIONS}
        value={watchedValues.finance_term}
        onSelect={(v) => setValue('finance_term', v as number)}
      />
      <ControlledInput
        control={control}
        name="start_date"
        label="Start Date"
        placeholder="YYYY-MM-DD"
      />
    </FormSection>
  );
}

function ContactSection({ control }: { control: Control<FinanceFormData> }) {
  return (
    <FormSection title="Contact Information" collapsible defaultCollapsed>
      <ControlledInput
        control={control}
        name="sales_consultant"
        label="Sales Consultant"
        placeholder="John Smith"
      />
      <ControlledInput
        control={control}
        name="dealership_name"
        label="Dealership"
        placeholder="ABC Motors"
      />
      <ControlledInput
        control={control}
        name="contact_email"
        label="Email"
        placeholder="john@dealer.com"
        keyboardType="email-address"
        autoCapitalize="none"
      />
      <ControlledInput
        control={control}
        name="contact_phone"
        label="Phone"
        placeholder="(555) 123-4567"
        keyboardType="phone-pad"
      />
    </FormSection>
  );
}

function NotesSection({ control }: { control: Control<FinanceFormData> }) {
  return (
    <FormSection title="Notes" collapsible defaultCollapsed>
      <ControlledInput
        control={control}
        name="notes"
        label="Notes"
        placeholder="Additional notes..."
        multiline
        numberOfLines={4}
      />
    </FormSection>
  );
}

function AdvancedSection({ control }: { control: Control<FinanceFormData> }) {
  return (
    <FormSection title="Advanced" collapsible defaultCollapsed>
      <ControlledInput
        control={control}
        name="extra_payments_json"
        label="Extra Payments (JSON)"
        placeholder='[{"startMonth": 1, "endMonth": 12, "paymentAmount": 100}]'
        multiline
        numberOfLines={3}
      />
    </FormSection>
  );
}

function ActionBar({
  onSubmit,
  onCancel,
  isSubmitting,
  submitLabel,
}: {
  onSubmit: () => void;
  onCancel?: () => void;
  isSubmitting: boolean;
  submitLabel: string;
}) {
  return (
    <View className="border-t border-neutral-200 bg-white p-4 dark:border-neutral-700 dark:bg-neutral-800">
      <View className="flex-row gap-3">
        {onCancel && (
          <View className="flex-1">
            <Button label="Cancel" variant="outline" onPress={onCancel} />
          </View>
        )}
        <View className="flex-1">
          <Button
            label={isSubmitting ? 'Saving...' : submitLabel}
            onPress={onSubmit}
            disabled={isSubmitting}
          />
        </View>
      </View>
    </View>
  );
}

// web/src/components/FinanceForm.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import FormField from './FormField.vue'
import BaseButton from './BaseButton.vue'
import { FinanceFormData, FormErrors, vehicleTypeOptions } from '@/types'

interface Props {
  form: FinanceFormData
  errors: FormErrors
  loading: boolean
  title: string
  backUrl: string
  isEdit?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  isEdit: false,
})

defineEmits<{
  submit: []
}>()
</script>

<template>
  <div class="bg-white rounded-lg border border-gray-200 shadow-sm p-6 bg-white">
    <form @submit.prevent="$emit('submit')" class="space-y-6">
      <!-- Basic Information -->
      <div>
        <h3 class="text-lg font-medium text-gray-900 mb-4">Basic Information</h3>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-3">
          <FormField
            v-model="form.sheet_name"
            name="sheet_name"
            label="Estimate Name"
            :error="errors.sheet_name"
          />

          <FormField
            v-model="form.dealership_name"
            name="dealership_name"
            label="Dealership"
            :error="errors.dealership_name"
          />

          <FormField
            v-model="form.vehicle_type"
            name="vehicle_type"
            label="Vehicle Type"
            type="select"
            :options="vehicleTypeOptions"
            :error="errors.vehicle_type"
          />
        </div>
      </div>

      <!-- Contact Information (Edit mode only) -->
      <div class="border-t border-gray-200 pt-6">
        <h3 class="text-lg font-medium text-gray-900 mb-4">Contact Information</h3>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-3">
          <FormField
            v-model="form.sales_consultant"
            name="sales_consultant"
            label="Sales Consultant"
            :error="errors.sales_consultant"
          />

          <FormField
            v-model="form.contact_email"
            name="contact_email"
            label="Contact Email"
            type="email"
            :error="errors.contact_email"
          />

          <FormField
            v-model="form.contact_phone"
            name="contact_phone"
            label="Contact Phone"
            type="tel"
            :error="errors.contact_phone"
          />
        </div>
      </div>

      <!-- Vehicle Information -->
      <div class="border-t border-gray-200 pt-6">
        <h3 class="text-lg font-medium text-gray-900 mb-4">Vehicle Information</h3>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <FormField
            v-model="form.vehicle_year"
            name="vehicle_year"
            label="Year"
            type="number"
            :min="1900"
            :max="2030"
            :error="errors.vehicle_year"
          />

          <FormField
            v-model="form.vehicle_make"
            name="vehicle_make"
            label="Make"
            :error="errors.vehicle_make"
          />

          <FormField
            v-model="form.vehicle_model"
            name="vehicle_model"
            label="Model"
            :error="errors.vehicle_model"
          />

          <FormField
            v-model="form.vehicle_trim"
            name="vehicle_trim"
            label="Trim"
            :error="errors.vehicle_trim"
          />
        </div>
      </div>

      <!-- Pricing Information -->
      <div class="border-t border-gray-200 pt-6">
        <h3 class="text-lg font-medium text-gray-900 mb-4">Pricing Information</h3>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <FormField
            v-model="form.msrp"
            name="msrp"
            label="MSRP"
            type="currency"
            :error="errors.msrp"
          />

          <FormField
            v-model="form.fees"
            name="fees"
            label="Fees"
            type="currency"
            :error="errors.fees"
          />

          <FormField
            v-model="form.discounts"
            name="discounts"
            label="Discounts"
            type="currency"
            :error="errors.discounts"
          />

          <FormField
            v-model="form.rebates"
            name="rebates"
            label="Rebates"
            type="currency"
            :error="errors.rebates"
          />

          <FormField
            v-model="form.down_payment"
            name="down_payment"
            label="Down Payment"
            type="currency"
            :error="errors.down_payment"
          />

          <FormField
            v-model="form.sales_tax_percent"
            name="sales_tax_percent"
            label="Sales Tax Percent"
            type="percentage"
            :error="errors.sales_tax_percent"
          />
        </div>
      </div>

      <!-- Finance Terms -->
      <div class="border-t border-gray-200 pt-6">
        <h3 class="text-lg font-medium text-gray-900 mb-4">Finance Terms</h3>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <FormField
            v-model="form.interest_rate"
            name="interest_rate"
            label="Interest Rate"
            type="percentage"
            :error="errors.interest_rate"
          />

          <FormField
            v-model="form.finance_term"
            name="finance_term"
            label="Finance Term (Months)"
            type="number"
            :min="1"
            :max="120"
            :error="errors.finance_term"
          />

          <FormField
            name="start_date"
            label="Start Date"
            type="date"
            :error="errors.start_date"
            :model-value="form.start_date ? form.start_date.substring(0, 10) : ''"
            @input="
              (event: any) => {
                form.start_date = event.target.value
              }
            "
          />
        </div>
      </div>

      <!-- Notes -->
      <div class="border-t border-gray-200 pt-6">
        <FormField
          v-model="form.notes"
          name="notes"
          label="Notes"
          type="textarea"
          :error="errors.notes"
        />
      </div>

      <!-- Submit Button -->
      <div v-if="!isEdit" class="flex justify-end space-x-3">
        <RouterLink
          :to="backUrl"
          class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          Cancel
        </RouterLink>
        <BaseButton type="submit" :disabled="loading" variant="primary">
          <svg
            v-if="loading"
            class="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
          >
            <circle
              class="opacity-25"
              cx="12"
              cy="12"
              r="10"
              stroke="currentColor"
              stroke-width="4"
            ></circle>
            <path
              class="opacity-75"
              fill="currentColor"
              d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
            ></path>
          </svg>
          {{ loading ? 'Creating...' : 'Create Finance Estimate' }}
        </BaseButton>
      </div>
    </form>
  </div>
</template>
