// app/src/components/ui/section-header.tsx
import * as React from 'react';
import { View } from 'react-native';

import { Text } from './text';

type IconComponent = React.ComponentType<{ color?: string; size?: number; width?: number; height?: number }>;

interface SectionHeaderProps {
	/** Small caps eyebrow label, e.g. "Watch · Price ledger" */
	eyebrow?: string;
	/** Editorial serif title */
	title: string;
	/** Optional supporting description (right-side aside on web; below title on mobile) */
	description?: string;
	/** Optional icon for the inset chip */
	icon?: IconComponent;
	/** Optional running issue/index number */
	index?: string | number;
	/** Compact variant for sub-pages */
	variant?: 'editorial' | 'compact';
	/** Optional action node (button, link) rendered below the hairline divider */
	actions?: React.ReactNode;
	/** Optional aside content rendered below the description */
	aside?: React.ReactNode;
}

/**
 * Editorial section header — eyebrow + serif title + description + hairline + actions.
 * Mirrors the web SectionHeader component.
 */
export function SectionHeader({
	eyebrow,
	title,
	description,
	icon: Icon,
	index,
	variant = 'editorial',
	actions,
	aside,
}: SectionHeaderProps) {
	const isCompact = variant === 'compact';
	return (
		<View className={`px-4 sm:px-6 lg:px-8 ${isCompact ? 'py-6' : 'pb-7 pt-8'}`}>
			{/* Top row: eyebrow + chip + index */}
			<View className="mb-5 flex-row items-center justify-between">
				<View className="flex-row items-center gap-3">
					{Icon ? (
						<View className="size-8 items-center justify-center rounded-md bg-primary dark:bg-text-primary-dark">
							<Icon color="#FCFAF5" width={16} height={16} />
						</View>
					) : null}
					<Text className="text-[10px] font-semibold uppercase tracking-eyebrow text-text-muted-light dark:text-text-muted-dark">
						{eyebrow ?? '·'}
					</Text>
				</View>
				{index !== undefined && index !== null ? (
					<Text className="font-mono text-xs text-text-muted-light dark:text-text-muted-dark">
						№ {String(index).padStart(2, '0')}
					</Text>
				) : null}
			</View>

			{/* Title */}
			<Text
				className={`font-display tracking-tightest text-text-primary-light dark:text-text-primary-dark ${
					isCompact ? 'text-3xl' : 'text-4xl'
				}`}
				style={{ lineHeight: isCompact ? 36 : 44 }}
			>
				{title}
			</Text>

			{/* Description */}
			{description ? (
				<View className="mt-4 border-l border-border-light pl-4 dark:border-border-dark">
					<Text className="text-sm leading-5 text-text-muted-light dark:text-text-muted-dark">{description}</Text>
				</View>
			) : null}

			{/* Aside content */}
			{aside ? <View className="mt-4">{aside}</View> : null}

			{/* Hairline divider + actions */}
			{(actions || !isCompact) && (
				<View className="mt-6 flex-row items-center gap-4">
					<View className="h-px flex-1 bg-border-light dark:bg-border-dark" />
					{actions ? <View className="flex-row items-center gap-2">{actions}</View> : null}
				</View>
			)}
		</View>
	);
}

// web/src/components/SectionHeader.vue
<script setup lang="ts">
import { type Component, computed } from 'vue';

interface Props {
	/** Small caps section label, e.g. "Watch", "Compute / Financing" */
	eyebrow?: string;
	/** Editorial serif title */
	title: string;
	/** Optional supporting description */
	description?: string;
	/** Optional running issue/index number, pure ornament that lends a magazine feel */
	index?: string | number;
	/** Optional Heroicon component for the inset navy chip */
	icon?: Component;
	/** Variant chooses ornament style */
	variant?: 'editorial' | 'compact';
}

const props = withDefaults(defineProps<Props>(), {
	variant: 'editorial',
	index: undefined,
});

const isCompact = computed(() => props.variant === 'compact');
</script>

<template>
	<header class="relative" :class="isCompact ? 'pt-6 pb-6' : 'pt-10 lg:pt-14 pb-8 lg:pb-10'">
		<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
			<!-- Top eyebrow row: section label + optional running index -->
			<div class="flex items-baseline justify-between mb-5 lg:mb-7">
				<div class="flex items-center gap-3 fade-up">
					<span v-if="icon" class="inline-flex items-center justify-center w-8 h-8 rounded-md bg-primary text-surface">
						<component :is="icon" class="h-4 w-4" />
					</span>
					<span class="eyebrow">{{ eyebrow || '·' }}</span>
				</div>
				<span v-if="index" class="numeral text-xs text-text-muted">№ {{ index }}</span>
			</div>

			<!-- Title + description split -->
			<div class="grid grid-cols-12 gap-6 lg:gap-10 items-end">
				<div class="col-span-12 lg:col-span-8 fade-up fade-up-1">
					<h1
						class="font-display text-primary tracking-tightest leading-[0.95]"
						:class="
							isCompact
								? 'text-3xl sm:text-4xl lg:text-5xl font-medium'
								: 'text-4xl sm:text-5xl lg:text-[3.75rem] font-medium'
						"
					>
						{{ title }}
					</h1>
				</div>
				<div class="col-span-12 lg:col-span-4 lg:pb-1 fade-up fade-up-2">
					<p
						v-if="description"
						class="text-sm sm:text-base text-text-muted leading-relaxed border-l border-border pl-4"
					>
						{{ description }}
					</p>
					<slot name="aside" />
				</div>
			</div>

			<!-- Bottom hairline divider with optional action slot floating right -->
			<div class="mt-8 lg:mt-10 flex items-center gap-4 fade-up fade-up-3">
				<div class="h-px flex-1 bg-border" />
				<div class="flex items-center gap-2 flex-shrink-0">
					<slot name="actions" />
				</div>
			</div>
		</div>
	</header>
</template>
