// app/src/app/(auth)/register.tsx
import { zodResolver } from '@hookform/resolvers/zod';
import { Link, router } from 'expo-router';
import React from 'react';
import { useForm } from 'react-hook-form';
import { showMessage } from 'react-native-flash-message';
import { z } from 'zod';

import { useRegister } from '@/api/auth/use-auth';
import {
  Button,
  ControlledInput,
  Pressable,
  SafeAreaView,
  ScrollView,
  Text,
  View,
} from '@/components/ui';

const registerSchema = z
  .object({
    first_name: z.string().min(1, 'First name is required'),
    last_name: z.string().min(1, 'Last name is required'),
    email: z.string().email('Invalid email address'),
    password: z.string().min(8, 'Password must be at least 8 characters'),
    password_confirmation: z.string(),
  })
  .refine((data) => data.password === data.password_confirmation, {
    message: 'Passwords do not match',
    path: ['password_confirmation'],
  });

type RegisterFormData = z.infer<typeof registerSchema>;

export default function RegisterScreen() {
  const { mutate: register, isPending } = useRegister();

  const { control, handleSubmit } = useForm<RegisterFormData>({
    resolver: zodResolver(registerSchema),
    defaultValues: {
      first_name: '',
      last_name: '',
      email: '',
      password: '',
      password_confirmation: '',
    },
  });

  const onSubmit = (data: RegisterFormData) => {
    register(data, {
      onSuccess: () => {
        showMessage({
          message: 'Account Created',
          description: 'Please check your email to verify your account',
          type: 'success',
        });
        router.replace('/(auth)/verify-email');
      },
      onError: (error) => {
        showMessage({
          message: 'Registration Failed',
          description: error.message || 'Could not create account',
          type: 'danger',
        });
      },
    });
  };

  return (
    <SafeAreaView className="flex-1 bg-white dark:bg-neutral-900">
      <ScrollView
        className="flex-1"
        contentContainerStyle={{ flexGrow: 1, padding: 24 }}
        keyboardShouldPersistTaps="handled"
      >
        {/* Header */}
        <View className="my-8">
          <Text className="text-3xl font-bold text-neutral-900 dark:text-white">
            Create Account
          </Text>
          <Text className="mt-2 text-neutral-600 dark:text-neutral-400">
            Sign up to get started with Sneaky Salesman
          </Text>
        </View>

        {/* Form */}
        <View className="gap-4">
          <View className="flex-row gap-4">
            <View className="flex-1">
              <ControlledInput
                control={control}
                name="first_name"
                label="First Name"
                placeholder="John"
                autoCapitalize="words"
              />
            </View>
            <View className="flex-1">
              <ControlledInput
                control={control}
                name="last_name"
                label="Last Name"
                placeholder="Doe"
                autoCapitalize="words"
              />
            </View>
          </View>

          <ControlledInput
            control={control}
            name="email"
            label="Email"
            placeholder="john@example.com"
            keyboardType="email-address"
            autoCapitalize="none"
            autoComplete="email"
          />

          <ControlledInput
            control={control}
            name="password"
            label="Password"
            placeholder="Min 8 characters"
            secureTextEntry
            autoComplete="new-password"
          />

          <ControlledInput
            control={control}
            name="password_confirmation"
            label="Confirm Password"
            placeholder="Confirm your password"
            secureTextEntry
            autoComplete="new-password"
          />
        </View>

        {/* Submit Button */}
        <View className="mt-8">
          <Button
            label={isPending ? 'Creating Account...' : 'Create Account'}
            onPress={handleSubmit(onSubmit)}
            disabled={isPending}
          />
        </View>

        {/* Login Link */}
        <View className="mt-6 flex-row items-center justify-center">
          <Text className="text-neutral-600 dark:text-neutral-400">
            Already have an account?{' '}
          </Text>
          <Link href="/(auth)/login" asChild>
            <Pressable>
              <Text className="font-semibold text-primary-600">Sign In</Text>
            </Pressable>
          </Link>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

// resources/js/Pages/Auth/Register.vue
<script setup lang="ts">
import AuthLayout from '@/Layouts/AuthLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

const form = useForm({
    first_name: '',
    last_name: '',
    email: '',
    password: '',
    password_confirmation: '',
});

const submit = () => {
    form.post(route('register'), {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
};
</script>

<template>
    <AuthLayout>
        <Head title="Join the Renegades" />

        <div class="text-center mb-6">
            <h2 class="text-2xl font-bold text-gray-900 mb-2">Join the Renegades</h2>
            <p class="text-gray-600">Create your account and start outsmarting the sales game</p>
        </div>

        <form @submit.prevent="submit" class="space-y-5">
            <div class="grid grid-cols-2 gap-4">
                <div>
                    <InputLabel for="first_name" value="First Name" class="text-gray-900 font-medium" />
                    <TextInput
                        id="first_name"
                        type="text"
                        class="mt-2 block w-full rounded-lg border-gray-300 focus:border-primary focus:ring-primary"
                        v-model="form.first_name"
                        required
                        autofocus
                        autocomplete="given-name"
                        placeholder="John"
                    />
                    <InputError class="mt-2" :message="form.errors.first_name" />
                </div>
                <div>
                    <InputLabel for="last_name" value="Last Name" class="text-gray-900 font-medium" />
                    <TextInput
                        id="last_name"
                        type="text"
                        class="mt-2 block w-full rounded-lg border-gray-300 focus:border-primary focus:ring-primary"
                        v-model="form.last_name"
                        required
                        autocomplete="family-name"
                        placeholder="Doe"
                    />
                    <InputError class="mt-2" :message="form.errors.last_name" />
                </div>
            </div>

            <div>
                <InputLabel for="email" value="Email Address" class="text-gray-900 font-medium" />
                <TextInput
                    id="email"
                    type="email"
                    class="mt-2 block w-full rounded-lg border-gray-300 focus:border-primary focus:ring-primary"
                    v-model="form.email"
                    required
                    autocomplete="username"
                    placeholder="john@example.com"
                />
                <InputError class="mt-2" :message="form.errors.email" />
            </div>

            <div>
                <InputLabel for="password" value="Password" class="text-gray-900 font-medium" />
                <TextInput
                    id="password"
                    type="password"
                    class="mt-2 block w-full rounded-lg border-gray-300 focus:border-primary focus:ring-primary"
                    v-model="form.password"
                    required
                    autocomplete="new-password"
                    placeholder="Create a strong password"
                />
                <InputError class="mt-2" :message="form.errors.password" />
            </div>

            <div>
                <InputLabel for="password_confirmation" value="Confirm Password" class="text-gray-900 font-medium" />
                <TextInput
                    id="password_confirmation"
                    type="password"
                    class="mt-2 block w-full rounded-lg border-gray-300 focus:border-primary focus:ring-primary"
                    v-model="form.password_confirmation"
                    required
                    autocomplete="new-password"
                    placeholder="Confirm your password"
                />
                <InputError class="mt-2" :message="form.errors.password_confirmation" />
            </div>

            <div>
                <PrimaryButton
                    class="w-full bg-primary hover:bg-primary-shade-1 text-white flex flex-row justify-center py-3 rounded-lg font-medium transition-all duration-150 hover:neon-glow"
                    :class="{ 'opacity-50 cursor-not-allowed': form.processing }"
                    :disabled="form.processing"
                >
                    <span v-if="form.processing">Creating Account...</span>
                    <span v-else>Join the Renegades</span>
                </PrimaryButton>
            </div>

            <div class="text-center pt-4 border-t border-gray-200">
                <p class="text-sm text-gray-600">
                    Already have an account?
                    <Link :href="route('login')" class="text-primary hover:text-primary-shade-1 font-medium transition-colors">
                        Sign in here
                    </Link>
                </p>
            </div>
        </form>
    </AuthLayout>
</template>
